# Generated by Django 2.2.16 on 2022-10-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221001_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('confirmation_code', models.CharField(blank=True, max_length=555)),
            ],
        ),
    ]
