# Generated by Django 2.2.16 on 2022-10-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221002_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
